apiPort: 0
bindings:
  - name: new-bridge-iDYVu
    properties: {}
    sources:
      connections:
        - address: localhost:50000
          channel: redis
      kind: source.queue
    targets:
      connections:
        - address: localhost:50000
          channel: redis-2
      kind: target.query
logLevel: "debug"

